PRAGMA foreign_keys = ON;
ALTER TABLE meliponaries ADD COLUMN archived_at TEXT;
ALTER TABLE meliponaries ADD COLUMN archive_reason TEXT;
ALTER TABLE species ADD COLUMN archived_at TEXT;
ALTER TABLE species ADD COLUMN archive_reason TEXT;
ALTER TABLE inspections ADD COLUMN corrected_at TEXT;
ALTER TABLE inspections ADD COLUMN voided_at TEXT;
ALTER TABLE inspections ADD COLUMN void_reason TEXT;
ALTER TABLE feedings ADD COLUMN corrected_at TEXT;
ALTER TABLE feedings ADD COLUMN voided_at TEXT;
ALTER TABLE feedings ADD COLUMN void_reason TEXT;
ALTER TABLE production_records ADD COLUMN corrected_at TEXT;
ALTER TABLE production_records ADD COLUMN voided_at TEXT;
ALTER TABLE production_records ADD COLUMN void_reason TEXT;
ALTER TABLE box_maintenance_records ADD COLUMN corrected_at TEXT;
ALTER TABLE box_maintenance_records ADD COLUMN voided_at TEXT;
ALTER TABLE box_maintenance_records ADD COLUMN void_reason TEXT;
ALTER TABLE colony_events ADD COLUMN corrected_at TEXT;
ALTER TABLE colony_events ADD COLUMN voided_at TEXT;
ALTER TABLE colony_events ADD COLUMN void_reason TEXT;
ALTER TABLE colony_movements ADD COLUMN corrected_at TEXT;
ALTER TABLE colony_movements ADD COLUMN voided_at TEXT;
ALTER TABLE colony_movements ADD COLUMN void_reason TEXT;
ALTER TABLE colony_movements ADD COLUMN reversed_at TEXT;
ALTER TABLE colony_movements ADD COLUMN reversal_reason TEXT;
ALTER TABLE movement_documents ADD COLUMN corrected_at TEXT;
ALTER TABLE movement_documents ADD COLUMN voided_at TEXT;
ALTER TABLE movement_documents ADD COLUMN void_reason TEXT;
ALTER TABLE colony_divisions ADD COLUMN corrected_at TEXT;
ALTER TABLE colony_divisions ADD COLUMN voided_at TEXT;
ALTER TABLE colony_divisions ADD COLUMN void_reason TEXT;
ALTER TABLE colony_lifecycle_records ADD COLUMN reversed_at TEXT;
ALTER TABLE colony_lifecycle_records ADD COLUMN reversal_reason TEXT;
ALTER TABLE colony_box_occupancies ADD COLUMN corrected_at TEXT;
CREATE TABLE audit_records(id TEXT PRIMARY KEY NOT NULL,entity_type TEXT NOT NULL CHECK(length(trim(entity_type))>0),entity_id TEXT NOT NULL CHECK(length(trim(entity_id))>0),action TEXT NOT NULL CHECK(length(trim(action))>0),changed_at TEXT NOT NULL,reason TEXT NOT NULL CHECK(length(trim(reason))>0),before_json TEXT,after_json TEXT,actor TEXT NOT NULL DEFAULT 'local_user',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_audit_entity_history ON audit_records(entity_type,entity_id,changed_at DESC,created_at DESC);
CREATE INDEX ix_inspections_valid_latest ON inspections(colony_id,inspected_at DESC,created_at DESC) WHERE voided_at IS NULL;
CREATE INDEX ix_feedings_valid_latest ON feedings(colony_id,fed_at DESC,created_at DESC) WHERE voided_at IS NULL;
CREATE INDEX ix_production_valid_history ON production_records(colony_id,harvested_at DESC) WHERE voided_at IS NULL;
CREATE INDEX ix_maintenance_valid_history ON box_maintenance_records(box_id,maintained_at DESC) WHERE voided_at IS NULL;
CREATE INDEX ix_movements_effective_history ON colony_movements(colony_id,moved_at DESC) WHERE voided_at IS NULL AND reversed_at IS NULL;
CREATE INDEX ix_lifecycle_effective_history ON colony_lifecycle_records(colony_id,occurred_at DESC) WHERE reversed_at IS NULL;
CREATE TRIGGER trg_internal_transfer_requires_active_meliponary BEFORE INSERT ON colony_movements FOR EACH ROW WHEN NEW.movement_type='internal_transfer' AND COALESCE((SELECT archived_at IS NULL FROM meliponaries WHERE id=NEW.to_meliponary_id),0)=0 BEGIN SELECT RAISE(ABORT,'Meliponário de destino indisponível para transferência.'); END;
CREATE TRIGGER trg_manual_event_not_future BEFORE INSERT ON colony_events FOR EACH ROW WHEN NEW.occurred_at>datetime('now','localtime') BEGIN SELECT RAISE(ABORT,'Evento manual não pode ser registrado no futuro.'); END;
