import { useEffect, useState, type FormEvent } from "react";
import { ConfirmDialog } from "../components/ConfirmDialog";
import { Dialog } from "../components/Dialog";
import { PageToolbar } from "../components/PageToolbar";
import { ReasonDialog } from "../components/ReasonDialog";
import { RecordActions } from "../components/RecordActions";
import { RecordStateBadge } from "../components/RecordStateBadge";
import type { RecordStateMap } from "../hooks/useAppData";
import { listBoxMaintenance, listColonyInspections, listColonyPhotos } from "../lib/api";
import type { BoxMaintenance, Colony, CorrectMaintenanceInput, CreateBoxMaintenanceInput, HiveBox, ImportInspectionPhotoInput, Inspection, InspectionPhoto, VoidRecordInput } from "../types";

type Props = {
  colonies: Colony[];
  boxes: HiveBox[];
  busy: boolean;
  recordStateMap: RecordStateMap;
  onImportPhoto: (input: ImportInspectionPhotoInput) => Promise<boolean>;
  onDeletePhoto: (photoId: string) => Promise<boolean>;
  onCreateMaintenance: (input: CreateBoxMaintenanceInput) => Promise<boolean>;
  onCorrectMaintenance: (input: CorrectMaintenanceInput) => Promise<boolean>;
  onVoidMaintenance: (input: VoidRecordInput) => Promise<boolean>;
};
const photoInitial: ImportInspectionPhotoInput = { inspectionId: "", sourcePath: "", capturedAt: "", notes: "" };
const maintenanceInitial: CreateBoxMaintenanceInput = { boxId: "", maintainedAt: "", maintenanceType: "inspection", description: "", performedBy: "", nextMaintenanceAt: "" };
const maintenanceTypes = [["cleaning", "Limpeza"], ["repair", "Reparo"], ["painting", "Pintura"], ["waterproofing", "Impermeabilização"], ["roof", "Cobertura"], ["entrance", "Entrada"], ["internal_structure", "Estrutura interna"], ["inspection", "Revisão da caixa"], ["other", "Outro"]] as const;

export function AssetsPage({ colonies, boxes, busy, recordStateMap, onImportPhoto, onDeletePhoto, onCreateMaintenance, onCorrectMaintenance, onVoidMaintenance }: Props) {
  const [selectedColonyId, setSelectedColonyId] = useState("");
  const [selectedBoxId, setSelectedBoxId] = useState("");
  const [photoForm, setPhotoForm] = useState<ImportInspectionPhotoInput>(photoInitial);
  const [inspections, setInspections] = useState<Inspection[]>([]);
  const [photos, setPhotos] = useState<InspectionPhoto[]>([]);
  const [photoLoading, setPhotoLoading] = useState(false);
  const [maintenanceForm, setMaintenanceForm] = useState<CreateBoxMaintenanceInput>(maintenanceInitial);
  const [costValue, setCostValue] = useState("");
  const [maintenance, setMaintenance] = useState<BoxMaintenance[]>([]);
  const [maintenanceLoading, setMaintenanceLoading] = useState(false);
  const [photoDialog, setPhotoDialog] = useState(false);
  const [maintenanceDialog, setMaintenanceDialog] = useState(false);
  const [deletePhotoId, setDeletePhotoId] = useState<string | null>(null);
  const [maintenanceDetail, setMaintenanceDetail] = useState<BoxMaintenance | null>(null);
  const [editMaintenance, setEditMaintenance] = useState<CorrectMaintenanceInput | null>(null);
  const [voidMaintenance, setVoidMaintenance] = useState<BoxMaintenance | null>(null);

  useEffect(() => {
    let cancelled = false;
    if (!selectedColonyId) { setInspections([]); setPhotos([]); return; }
    setPhotoLoading(true);
    Promise.all([listColonyInspections(selectedColonyId), listColonyPhotos(selectedColonyId)]).then(([inspectionItems, photoItems]) => { if (!cancelled) { setInspections(inspectionItems); setPhotos(photoItems); } }).finally(() => { if (!cancelled) setPhotoLoading(false); });
    return () => { cancelled = true; };
  }, [selectedColonyId]);

  useEffect(() => { void reloadMaintenance(selectedBoxId); }, [selectedBoxId]);
  async function reloadPhotos() { if (selectedColonyId) setPhotos(await listColonyPhotos(selectedColonyId)); }
  async function reloadMaintenance(boxId = selectedBoxId) { if (!boxId) { setMaintenance([]); return; } setMaintenanceLoading(true); try { setMaintenance(await listBoxMaintenance(boxId)); } finally { setMaintenanceLoading(false); } }
  function openPhoto() { const firstInspection = inspections[0]?.id || ""; setPhotoForm({ ...photoInitial, inspectionId: firstInspection }); setPhotoDialog(true); }
  function openMaintenance() { setMaintenanceForm({ ...maintenanceInitial, boxId: selectedBoxId }); setCostValue(""); setMaintenanceDialog(true); }
  function beginCorrect(item: BoxMaintenance) { setEditMaintenance({ id: item.id, reason: "", boxId: item.boxId, maintainedAt: toInputDateTime(item.maintainedAt), maintenanceType: item.maintenanceType, description: item.description || "", performedBy: item.performedBy || "", cost: item.cost ?? undefined, nextMaintenanceAt: item.nextMaintenanceAt ? toInputDateTime(item.nextMaintenanceAt) : "" }); }

  async function submitPhoto(event: FormEvent) { event.preventDefault(); const input = { ...photoForm, capturedAt: normalizeDateTime(photoForm.capturedAt) }; if (await onImportPhoto(input)) { setPhotoDialog(false); setPhotoForm(photoInitial); await reloadPhotos(); } }
  async function confirmRemovePhoto() { if (!deletePhotoId) return; if (await onDeletePhoto(deletePhotoId)) { setDeletePhotoId(null); await reloadPhotos(); } }
  async function submitMaintenance(event: FormEvent) { event.preventDefault(); const input: CreateBoxMaintenanceInput = { ...maintenanceForm, maintainedAt: normalizeDateTime(maintenanceForm.maintainedAt), nextMaintenanceAt: normalizeDateTime(maintenanceForm.nextMaintenanceAt), cost: costValue.trim() ? Number(costValue) : undefined }; if (await onCreateMaintenance(input)) { const boxId = maintenanceForm.boxId; setSelectedBoxId(boxId); setMaintenanceDialog(false); setMaintenanceForm(maintenanceInitial); setCostValue(""); await reloadMaintenance(boxId); } }
  async function submitMaintenanceCorrection(event: FormEvent) { event.preventDefault(); if (!editMaintenance) return; const payload: CorrectMaintenanceInput = { ...editMaintenance, maintainedAt: normalizeDateTime(editMaintenance.maintainedAt) || editMaintenance.maintainedAt, nextMaintenanceAt: normalizeDateTime(editMaintenance.nextMaintenanceAt) }; if (await onCorrectMaintenance(payload)) { setSelectedBoxId(payload.boxId); setEditMaintenance(null); await reloadMaintenance(payload.boxId); } }

  return <div className="page-stack">
    <PageToolbar title="Manutenção" description="Histórico físico das caixas. Fotos continuam acessíveis como contexto das inspeções." count={`${maintenance.length} manutenções · ${photos.length} fotos`} primaryAction={{ label: "Nova manutenção", onClick: openMaintenance, disabled: busy || boxes.length === 0 }}><button className="button-secondary" type="button" onClick={openPhoto} disabled={busy || !selectedColonyId || inspections.length === 0}>Importar foto de inspeção</button></PageToolbar>
    <div className="content-grid">
      <section className="panel wide-list"><div className="panel-heading"><h2>Histórico da caixa</h2><p>Correções revalidam data, caixa e próxima manutenção; anulações não apagam o registro.</p></div><label className="field"><span>Caixa</span><select value={selectedBoxId} onChange={(e) => setSelectedBoxId(e.target.value)}><option value="">Selecione...</option>{boxes.map((box) => <option value={box.id} key={box.id}>{box.code} {box.currentColonyCode ? `· ${box.currentColonyCode}` : "· vazia"}</option>)}</select></label>{!selectedBoxId ? <div className="empty-list section-gap">Selecione uma caixa para consultar o histórico.</div> : maintenanceLoading ? <div className="empty-list section-gap">Carregando manutenções...</div> : maintenance.length === 0 ? <div className="empty-list section-gap">Nenhuma manutenção registrada.</div> : <div className="table-wrap section-gap"><table className="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Colônia</th><th>Próxima</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{maintenance.map((item) => { const state = recordStateMap.get(`box_maintenance:${item.id}`); return <tr key={item.id} className={state?.voidedAt ? "voided-row" : undefined}><td><strong>{formatDateTime(item.maintainedAt)}</strong></td><td>{maintenanceLabel(item.maintenanceType)}</td><td>{item.colonyCode || "Caixa vazia"}</td><td>{item.nextMaintenanceAt ? formatDateTime(item.nextMaintenanceAt) : "—"}</td><td><RecordStateBadge state={state} /></td><td><RecordActions busy={busy} onOpen={() => setMaintenanceDetail(item)} onEdit={state?.voidedAt ? undefined : () => beginCorrect(item)} secondary={[{ label: "Anular", onClick: () => setVoidMaintenance(item), disabled: Boolean(state?.voidedAt), danger: true }]} /></td></tr>; })}</tbody></table></div>}</section>
      <section className="panel wide-list"><div className="panel-heading"><h2>Fotos de inspeção</h2><p>Fotos permanecem vinculadas à inspeção mesmo quando ela recebe correção administrativa.</p></div><label className="field"><span>Colônia</span><select value={selectedColonyId} onChange={(e) => setSelectedColonyId(e.target.value)}><option value="">Selecione...</option>{colonies.map((colony) => <option value={colony.id} key={colony.id}>{colony.code}</option>)}</select></label>{!selectedColonyId ? <div className="empty-list section-gap">Selecione uma colônia para consultar as fotos.</div> : photoLoading ? <div className="empty-list section-gap">Carregando fotos...</div> : photos.length === 0 ? <div className="empty-list section-gap">Nenhuma foto registrada para esta colônia.</div> : <div className="record-list section-gap">{photos.map((photo) => <article className="record-card" key={photo.id}><div className="record-title-row"><div><strong>{photo.originalName}</strong><span>{formatDateTime(photo.capturedAt)} · {formatBytes(photo.byteSize)}</span></div><button type="button" className="button-secondary" onClick={() => setDeletePhotoId(photo.id)} disabled={busy}>Remover</button></div><dl><div><dt>Formato</dt><dd>{photo.mimeType}</dd></div><div><dt>Inspeção</dt><dd>{photo.inspectionId.slice(0, 8)}…</dd></div></dl>{photo.notes && <p>{photo.notes}</p>}</article>)}</div>}</section>
    </div>

    <Dialog open={maintenanceDialog} onClose={() => !busy && setMaintenanceDialog(false)} title="Nova manutenção" description="O contexto da colônia ocupante é resolvido pela data informada." size="large"><form className="form-grid" onSubmit={submitMaintenance}><label className="field full"><span>Caixa</span><select autoFocus required value={maintenanceForm.boxId} onChange={(e) => setMaintenanceForm({ ...maintenanceForm, boxId: e.target.value })}><option value="">Selecione...</option>{boxes.map((box) => <option value={box.id} key={box.id}>{box.code} {box.currentColonyCode ? `· ${box.currentColonyCode}` : "· vazia"}</option>)}</select></label><label className="field"><span>Tipo</span><select value={maintenanceForm.maintenanceType} onChange={(e) => setMaintenanceForm({ ...maintenanceForm, maintenanceType: e.target.value })}>{maintenanceTypes.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Data e hora</span><input type="datetime-local" value={maintenanceForm.maintainedAt} onChange={(e) => setMaintenanceForm({ ...maintenanceForm, maintainedAt: e.target.value })} /></label><label className="field full"><span>Descrição</span><textarea rows={3} value={maintenanceForm.description} onChange={(e) => setMaintenanceForm({ ...maintenanceForm, description: e.target.value })} /></label><label className="field"><span>Responsável</span><input value={maintenanceForm.performedBy} onChange={(e) => setMaintenanceForm({ ...maintenanceForm, performedBy: e.target.value })} /></label><label className="field"><span>Custo opcional</span><input type="number" min="0" step="0.01" value={costValue} onChange={(e) => setCostValue(e.target.value)} /></label><label className="field full"><span>Próxima manutenção</span><input type="datetime-local" value={maintenanceForm.nextMaintenanceAt} onChange={(e) => setMaintenanceForm({ ...maintenanceForm, nextMaintenanceAt: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setMaintenanceDialog(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !maintenanceForm.boxId}>{busy ? "Salvando..." : "Registrar manutenção"}</button></div></form></Dialog>

    <Dialog open={Boolean(maintenanceDetail)} onClose={() => setMaintenanceDetail(null)} title="Manutenção da caixa" description={maintenanceDetail ? `${maintenanceDetail.boxCode} · ${formatDateTime(maintenanceDetail.maintainedAt)}` : ""} size="medium">{maintenanceDetail && <div className="detail-grid"><div><span>Tipo</span><strong>{maintenanceLabel(maintenanceDetail.maintenanceType)}</strong></div><div><span>Colônia</span><strong>{maintenanceDetail.colonyCode || "Caixa vazia"}</strong></div><div><span>Responsável</span><strong>{maintenanceDetail.performedBy || "—"}</strong></div><div><span>Custo</span><strong>{maintenanceDetail.cost != null ? `R$ ${maintenanceDetail.cost.toFixed(2)}` : "—"}</strong></div><div className="full"><span>Descrição</span><p>{maintenanceDetail.description || "—"}</p></div></div>}</Dialog>
    <Dialog open={Boolean(editMaintenance)} onClose={() => !busy && setEditMaintenance(null)} title="Corrigir manutenção" description="A correção recalcula o contexto histórico da caixa e registra antes/depois na auditoria." size="large">{editMaintenance && <form className="form-grid" onSubmit={submitMaintenanceCorrection}><label className="field full"><span>Caixa</span><select autoFocus required value={editMaintenance.boxId} onChange={(e) => setEditMaintenance({ ...editMaintenance, boxId: e.target.value })}>{boxes.map((box) => <option value={box.id} key={box.id}>{box.code}</option>)}</select></label><label className="field"><span>Tipo</span><select value={editMaintenance.maintenanceType} onChange={(e) => setEditMaintenance({ ...editMaintenance, maintenanceType: e.target.value })}>{maintenanceTypes.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Data e hora</span><input required type="datetime-local" value={editMaintenance.maintainedAt} onChange={(e) => setEditMaintenance({ ...editMaintenance, maintainedAt: e.target.value })} /></label><label className="field full"><span>Descrição</span><textarea rows={3} value={editMaintenance.description || ""} onChange={(e) => setEditMaintenance({ ...editMaintenance, description: e.target.value })} /></label><label className="field"><span>Responsável</span><input value={editMaintenance.performedBy || ""} onChange={(e) => setEditMaintenance({ ...editMaintenance, performedBy: e.target.value })} /></label><label className="field"><span>Custo</span><input type="number" min="0" step="0.01" value={editMaintenance.cost ?? ""} onChange={(e) => setEditMaintenance({ ...editMaintenance, cost: e.target.value ? Number(e.target.value) : undefined })} /></label><label className="field full"><span>Próxima manutenção</span><input type="datetime-local" value={editMaintenance.nextMaintenanceAt || ""} onChange={(e) => setEditMaintenance({ ...editMaintenance, nextMaintenanceAt: e.target.value })} /></label><label className="field full"><span>Motivo da correção</span><textarea required rows={3} value={editMaintenance.reason} onChange={(e) => setEditMaintenance({ ...editMaintenance, reason: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setEditMaintenance(null)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !editMaintenance.reason.trim()}>Salvar correção</button></div></form>}</Dialog>

    <Dialog open={photoDialog} onClose={() => !busy && setPhotoDialog(false)} title="Importar foto de inspeção" description="O backend copia o arquivo para o armazenamento gerenciado; o SQLite guarda os metadados." size="medium"><form className="form-grid" onSubmit={submitPhoto}><label className="field full"><span>Inspeção</span><select autoFocus required value={photoForm.inspectionId} onChange={(e) => setPhotoForm({ ...photoForm, inspectionId: e.target.value })}><option value="">Selecione...</option>{inspections.map((inspection) => <option value={inspection.id} key={inspection.id}>{formatDateTime(inspection.inspectedAt)} {inspection.boxCode ? `· ${inspection.boxCode}` : "· sem caixa"}</option>)}</select></label><label className="field full"><span>Caminho local da foto</span><input value={photoForm.sourcePath} onChange={(e) => setPhotoForm({ ...photoForm, sourcePath: e.target.value })} required /></label><label className="field full"><span>Data da captura opcional</span><input type="datetime-local" value={photoForm.capturedAt} onChange={(e) => setPhotoForm({ ...photoForm, capturedAt: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={2} value={photoForm.notes} onChange={(e) => setPhotoForm({ ...photoForm, notes: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setPhotoDialog(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !photoForm.inspectionId}>{busy ? "Importando..." : "Importar foto"}</button></div></form></Dialog>

    <ReasonDialog open={Boolean(voidMaintenance)} title="Anular manutenção" description={voidMaintenance ? `${voidMaintenance.boxCode} · ${formatDateTime(voidMaintenance.maintainedAt)}` : ""} confirmLabel="Anular registro" consequence="A manutenção permanecerá auditável, mas deixará de representar um fato operacional válido." danger busy={busy} onClose={() => setVoidMaintenance(null)} onConfirm={async (reason) => { if (!voidMaintenance) return false; const ok = await onVoidMaintenance({ id: voidMaintenance.id, reason }); if (ok) await reloadMaintenance(); return ok; }} />
    <ConfirmDialog open={deletePhotoId !== null} title="Remover foto da inspeção?" consequence="A foto será removida do armazenamento gerenciado. O restante do histórico da inspeção permanece intacto." confirmLabel="Remover foto" danger busy={busy} onCancel={() => setDeletePhotoId(null)} onConfirm={() => { void confirmRemovePhoto(); }} />
  </div>;
}
function normalizeDateTime(value?: string) { if (!value) return undefined; const normalized = value.replace("T", " "); return normalized.length === 16 ? `${normalized}:00` : normalized; }
function toInputDateTime(value: string) { return value.replace(" ", "T").slice(0, 16); }
function formatDateTime(value: string) { return value.replace("T", " ").slice(0, 16); }
function formatBytes(value: number) { if (value < 1024) return `${value} B`; if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`; return `${(value / (1024 * 1024)).toFixed(1)} MB`; }
function maintenanceLabel(value: string) { return maintenanceTypes.find(([key]) => key === value)?.[1] || value; }
