import { useMemo, useState, type FormEvent } from "react";
import { Dialog } from "../components/Dialog";
import { PageToolbar } from "../components/PageToolbar";
import { ReasonDialog } from "../components/ReasonDialog";
import { RecordActions } from "../components/RecordActions";
import { RecordWorkspace } from "../components/RecordWorkspace";
import type { Colony, CreateColonyInput, EditColonyInput, EntityActionInput, HiveBox, Meliponary, PlaceColonyInput, Species } from "../types";

type Props = {
  items: Colony[]; meliponaries: Meliponary[]; species: Species[]; boxes: HiveBox[]; busy: boolean;
  onCreate: (input: CreateColonyInput) => Promise<boolean>;
  onPlace: (input: PlaceColonyInput) => Promise<boolean>;
  onEdit: (input: EditColonyInput) => Promise<boolean>;
  onDelete: (input: EntityActionInput) => Promise<boolean>;
};
const originOptions = [["acquisition", "Aquisição"], ["multiplication", "Multiplicação"], ["transfer", "Transferência"], ["rescue", "Resgate"], ["authorized_capture", "Captura autorizada"], ["historical", "Registro histórico"], ["other", "Outra origem"]] as const;
const initialForm: CreateColonyInput = { meliponaryId: "", speciesId: "", code: "", originType: "acquisition", originNotes: "", installedAt: "", motherColonyId: "", notes: "" };
const initialPlacement: PlaceColonyInput = { colonyId: "", boxId: "", startedAt: "", reason: "", notes: "" };
const manageableStatuses = new Set(["active", "weak", "recovering"]);

export function ColoniesPage({ items, meliponaries, species, boxes, busy, onCreate, onPlace, onEdit, onDelete }: Props) {
  const [form, setForm] = useState<CreateColonyInput>(initialForm);
  const [placement, setPlacement] = useState<PlaceColonyInput>(initialPlacement);
  const [newOpen, setNewOpen] = useState(false);
  const [placementOpen, setPlacementOpen] = useState(false);
  const [editForm, setEditForm] = useState<EditColonyInput | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Colony | null>(null);
  const [search, setSearch] = useState("");
  const [detailId, setDetailId] = useState<string | null>(null);
  const activeMeliponaries = useMemo(() => meliponaries.filter((item) => !item.archivedAt), [meliponaries]);
  const activeSpecies = useMemo(() => species.filter((item) => !item.archivedAt), [species]);
  const archivedMeliponaryIds = useMemo(() => new Set(meliponaries.filter((item) => item.archivedAt).map((item) => item.id)), [meliponaries]);
  const meliponaryNames = useMemo(() => new Map(meliponaries.map((item) => [item.id, item.name])), [meliponaries]);
  const speciesNames = useMemo(() => new Map(species.map((item) => [item.id, item.commonName])), [species]);
  const selectedColony = items.find((item) => item.id === placement.colonyId);
  const detail = detailId ? items.find((item) => item.id === detailId) ?? null : null;
  const availableBoxes = boxes.filter((box) => box.status === "active" && !box.currentColonyCode && !archivedMeliponaryIds.has(box.meliponaryId) && (!selectedColony || box.meliponaryId === selectedColony.meliponaryId));
  const motherOptions = items.filter((item) => manageableStatuses.has(item.status) && (!form.meliponaryId || item.meliponaryId === form.meliponaryId) && (!form.speciesId || item.speciesId === form.speciesId));
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return query ? items.filter((item) => [item.code, item.currentBoxCode, speciesNames.get(item.speciesId), meliponaryNames.get(item.meliponaryId)].some((value) => value?.toLocaleLowerCase().includes(query))) : items; }, [items, meliponaryNames, search, speciesNames]);

  async function submitColony(event: FormEvent) { event.preventDefault(); if (await onCreate(form)) { setForm({ ...initialForm, meliponaryId: form.meliponaryId, speciesId: form.speciesId }); setNewOpen(false); } }
  async function submitPlacement(event: FormEvent) { event.preventDefault(); if (await onPlace(placement)) { setPlacement(initialPlacement); setPlacementOpen(false); } }
  function beginEdit(item: Colony) { setEditForm({ id: item.id, code: item.code, originNotes: item.originNotes || "", notes: item.notes || "", reason: "" }); }
  async function submitEdit(event: FormEvent) { event.preventDefault(); if (editForm && await onEdit(editForm)) setEditForm(null); }

  if (detail) return <RecordWorkspace backLabel="Colônias" title={`${detail.code} · ${speciesNames.get(detail.speciesId) || "Espécie"}`} subtitle={meliponaryNames.get(detail.meliponaryId) || "Meliponário"} onBack={() => setDetailId(null)}><div className="workspace-actions"><button type="button" onClick={() => beginEdit(detail)}>Editar dados descritivos</button></div><div className="summary-grid"><Summary label="Situação" value={translateStatus(detail.status)} /><Summary label="Caixa atual" value={detail.currentBoxCode || "Sem caixa"} /><Summary label="Origem" value={originLabel(detail.originType)} /><Summary label="Instalação" value={detail.installedAt || "Não informada"} /><Summary label="Colônia-mãe" value={detail.motherColonyId ? items.find((item) => item.id === detail.motherColonyId)?.code || detail.motherColonyId : "Sem vínculo"} /><Summary label="Detalhes da origem" value={detail.originNotes || "Sem detalhes"} /><Summary label="Observações" value={detail.notes || "Sem observações"} /></div><Dialog open={Boolean(editForm)} onClose={() => !busy && setEditForm(null)} title="Editar colônia" description="Espécie, meliponário, natureza da origem, maternidade e data de entrada não são reescritos por este formulário." size="medium">{editForm && <EditForm form={editForm} setForm={setEditForm} busy={busy} onSubmit={submitEdit} />}</Dialog></RecordWorkspace>;

  return <div className="page-stack">
    <PageToolbar title="Colônias" description="Identidade biológica, situação atual e localização física." count={`${items.length} cadastradas`} search={{ value: search, onChange: setSearch, placeholder: "Buscar colônia..." }} primaryAction={{ label: "Nova colônia", onClick: () => setNewOpen(true), disabled: busy || activeMeliponaries.length === 0 || activeSpecies.length === 0 }}><button className="button-secondary" type="button" onClick={() => setPlacementOpen(true)} disabled={busy || items.length === 0 || boxes.length === 0}>Colocar / mover em caixa</button></PageToolbar>
    {(activeMeliponaries.length === 0 || activeSpecies.length === 0) && <div className="inline-notice">Cadastre ou reative pelo menos um meliponário e uma espécie antes de criar colônias.</div>}
    <section className="panel wide-list"><div className="panel-heading"><h2>Plantel cadastrado</h2><p>Alterações biológicas ou de ciclo de vida usam fluxos próprios; edição aqui é estritamente cadastral.</p></div>{filtered.length === 0 ? <div className="empty-list">{items.length === 0 ? "Nenhuma colônia cadastrada ainda." : "Nenhuma colônia corresponde à busca."}</div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Código</th><th>Espécie</th><th>Meliponário</th><th>Caixa atual</th><th>Situação</th><th>Origem</th><th>Ações</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><strong>{item.code}</strong></td><td>{speciesNames.get(item.speciesId) || "Espécie"}</td><td>{meliponaryNames.get(item.meliponaryId) || "Meliponário"}</td><td>{item.currentBoxCode || "Sem caixa"}</td><td><span className={`badge status-${item.status}`}>{translateStatus(item.status)}</span></td><td>{originLabel(item.originType)}</td><td><RecordActions busy={busy} onOpen={() => setDetailId(item.id)} onEdit={() => beginEdit(item)} secondary={[{ label: "Excluir cadastro vazio", onClick: () => setDeleteTarget(item), danger: true }]} /></td></tr>)}</tbody></table></div>}</section>

    <Dialog open={newOpen} onClose={() => !busy && setNewOpen(false)} title="Nova colônia" description="Cadastre a entidade biológica; a caixa é vinculada separadamente." size="large"><form className="form-grid" onSubmit={submitColony}><label className="field"><span>Meliponário</span><select autoFocus required value={form.meliponaryId} onChange={(e) => setForm({ ...form, meliponaryId: e.target.value, motherColonyId: "" })}><option value="">Selecione...</option>{activeMeliponaries.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Espécie</span><select required value={form.speciesId} onChange={(e) => setForm({ ...form, speciesId: e.target.value, motherColonyId: "" })}><option value="">Selecione...</option>{activeSpecies.map((item) => <option value={item.id} key={item.id}>{item.commonName}</option>)}</select></label><label className="field"><span>Código</span><input required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></label><label className="field"><span>Origem</span><select value={form.originType} onChange={(e) => setForm({ ...form, originType: e.target.value })}>{originOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Data de instalação</span><input type="date" value={form.installedAt} onChange={(e) => setForm({ ...form, installedAt: e.target.value })} /></label><label className="field"><span>Colônia-mãe</span><select value={form.motherColonyId} onChange={(e) => setForm({ ...form, motherColonyId: e.target.value })}><option value="">Sem vínculo</option>{motherOptions.map((item) => <option value={item.id} key={item.id}>{item.code}</option>)}</select></label><label className="field full"><span>Detalhes da origem</span><input value={form.originNotes} onChange={(e) => setForm({ ...form, originNotes: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setNewOpen(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy}>Salvar colônia</button></div></form></Dialog>

    <Dialog open={placementOpen} onClose={() => !busy && setPlacementOpen(false)} title="Colocar ou mover para uma caixa" description="A ocupação anterior é encerrada e o histórico permanece preservado." size="medium"><form className="form-grid" onSubmit={submitPlacement}><label className="field full"><span>Colônia</span><select autoFocus required value={placement.colonyId} onChange={(e) => setPlacement({ ...placement, colonyId: e.target.value, boxId: "" })}><option value="">Selecione...</option>{items.filter((item) => manageableStatuses.has(item.status) && !archivedMeliponaryIds.has(item.meliponaryId)).map((item) => <option value={item.id} key={item.id}>{item.code} {item.currentBoxCode ? `· atual ${item.currentBoxCode}` : "· sem caixa"}</option>)}</select></label><label className="field full"><span>Caixa ativa e livre</span><select required value={placement.boxId} onChange={(e) => setPlacement({ ...placement, boxId: e.target.value })}><option value="">Selecione...</option>{availableBoxes.map((box) => <option value={box.id} key={box.id}>{box.code}</option>)}</select></label><label className="field"><span>Data e hora</span><input type="datetime-local" value={placement.startedAt} onChange={(e) => setPlacement({ ...placement, startedAt: e.target.value })} /></label><label className="field"><span>Motivo</span><input value={placement.reason} onChange={(e) => setPlacement({ ...placement, reason: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={3} value={placement.notes} onChange={(e) => setPlacement({ ...placement, notes: e.target.value })} /></label>{placement.colonyId && availableBoxes.length === 0 && <div className="inline-notice full">Não há caixa ativa e livre compatível com o meliponário desta colônia.</div>}<div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setPlacementOpen(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !placement.colonyId || availableBoxes.length === 0}>Registrar ocupação</button></div></form></Dialog>

    <Dialog open={Boolean(editForm)} onClose={() => !busy && setEditForm(null)} title="Editar colônia" description="Apenas dados descritivos seguros podem ser alterados aqui." size="medium">{editForm && <EditForm form={editForm} setForm={setEditForm} busy={busy} onSubmit={submitEdit} />}</Dialog>
    <ReasonDialog open={Boolean(deleteTarget)} title="Excluir colônia" description={deleteTarget?.code || ""} confirmLabel="Excluir definitivamente" consequence="Só uma colônia totalmente sem histórico, ocupação, genealogia ou fatos operacionais pode ser apagada. Qualquer vínculo bloqueia a operação." danger busy={busy} onClose={() => setDeleteTarget(null)} onConfirm={(reason) => deleteTarget ? onDelete({ id: deleteTarget.id, reason }) : false} />
  </div>;
}

function EditForm({ form, setForm, busy, onSubmit }: { form: EditColonyInput; setForm: (value: EditColonyInput) => void; busy: boolean; onSubmit: (event: FormEvent) => void }) { return <form className="form-grid" onSubmit={onSubmit}><label className="field full"><span>Código</span><input autoFocus required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></label><label className="field full"><span>Detalhes da origem</span><input value={form.originNotes} onChange={(e) => setForm({ ...form, originNotes: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><label className="field full"><span>Motivo da edição</span><textarea required rows={3} value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setForm({ ...form, reason: "" })} disabled={busy}>Limpar motivo</button><button type="submit" disabled={busy || !form.reason.trim()}>Salvar alteração</button></div></form>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="summary-item"><span>{label}</span><strong>{value}</strong></div>; }
function translateStatus(status: string) { const labels: Record<string, string> = { active: "Ativa", weak: "Fraca (legado)", recovering: "Em recuperação (legado)", lost: "Perdida", inactive: "Inativa", transferred: "Transferida" }; return labels[status] || status; }
function originLabel(origin: string) { return originOptions.find(([value]) => value === origin)?.[1] || origin; }
