import { useMemo, useState, type FormEvent } from "react";
import { Dialog } from "../components/Dialog";
import { PageToolbar } from "../components/PageToolbar";
import type { Colony, CreateColonyInput, HiveBox, Meliponary, PlaceColonyInput, Species } from "../types";

type ColoniesPageProps = { items: Colony[]; meliponaries: Meliponary[]; species: Species[]; boxes: HiveBox[]; busy: boolean; onCreate: (input: CreateColonyInput) => Promise<boolean>; onPlace: (input: PlaceColonyInput) => Promise<boolean>; };
const originOptions = [["acquisition", "Aquisição"], ["multiplication", "Multiplicação"], ["transfer", "Transferência"], ["rescue", "Resgate"], ["authorized_capture", "Captura autorizada"], ["historical", "Registro histórico"], ["other", "Outra origem"]] as const;
const initialForm: CreateColonyInput = { meliponaryId: "", speciesId: "", code: "", originType: "acquisition", originNotes: "", installedAt: "", motherColonyId: "", notes: "" };
const initialPlacement: PlaceColonyInput = { colonyId: "", boxId: "", startedAt: "", reason: "", notes: "" };
const manageableStatuses = new Set(["active", "weak", "recovering"]);

export function ColoniesPage({ items, meliponaries, species, boxes, busy, onCreate, onPlace }: ColoniesPageProps) {
  const [form, setForm] = useState<CreateColonyInput>(initialForm);
  const [placement, setPlacement] = useState<PlaceColonyInput>(initialPlacement);
  const [newOpen, setNewOpen] = useState(false);
  const [placementOpen, setPlacementOpen] = useState(false);
  const [search, setSearch] = useState("");
  const meliponaryNames = useMemo(() => new Map(meliponaries.map((item) => [item.id, item.name])), [meliponaries]);
  const speciesNames = useMemo(() => new Map(species.map((item) => [item.id, item.commonName])), [species]);
  const selectedColony = items.find((item) => item.id === placement.colonyId);
  const availableBoxes = boxes.filter((box) => box.status === "active" && !box.currentColonyCode && (!selectedColony || box.meliponaryId === selectedColony.meliponaryId));
  const motherOptions = items.filter((item) => (!form.meliponaryId || item.meliponaryId === form.meliponaryId) && (!form.speciesId || item.speciesId === form.speciesId));
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return query ? items.filter((item) => [item.code, item.currentBoxCode, speciesNames.get(item.speciesId), meliponaryNames.get(item.meliponaryId)].some((value) => value?.toLocaleLowerCase().includes(query))) : items; }, [items, meliponaryNames, search, speciesNames]);

  async function submitColony(event: FormEvent) { event.preventDefault(); if (await onCreate(form)) { setForm({ ...initialForm, meliponaryId: form.meliponaryId, speciesId: form.speciesId }); setNewOpen(false); } }
  async function submitPlacement(event: FormEvent) { event.preventDefault(); if (await onPlace(placement)) { setPlacement(initialPlacement); setPlacementOpen(false); } }

  return <div className="page-stack">
    <PageToolbar title="Colônias" description="Identidade biológica, situação atual e localização física." count={`${items.length} cadastradas`} search={{ value: search, onChange: setSearch, placeholder: "Buscar colônia..." }} primaryAction={{ label: "Nova colônia", onClick: () => setNewOpen(true), disabled: busy || meliponaries.length === 0 || species.length === 0 }}><button className="button-secondary" type="button" onClick={() => setPlacementOpen(true)} disabled={busy || items.length === 0 || boxes.length === 0}>Colocar / mover em caixa</button></PageToolbar>
    {(meliponaries.length === 0 || species.length === 0) && <div className="inline-notice">Cadastre pelo menos um meliponário e uma espécie antes de criar colônias.</div>}
    <section className="panel wide-list"><div className="panel-heading"><h2>Plantel cadastrado</h2><p>Estado atual com identidade, espécie e caixa mantidas separadamente.</p></div>{filtered.length === 0 ? <div className="empty-list">{items.length === 0 ? "Nenhuma colônia cadastrada ainda." : "Nenhuma colônia corresponde à busca."}</div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Código</th><th>Espécie</th><th>Meliponário</th><th>Caixa atual</th><th>Situação</th><th>Origem</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><strong>{item.code}</strong></td><td>{speciesNames.get(item.speciesId) || "Espécie"}</td><td>{meliponaryNames.get(item.meliponaryId) || "Meliponário"}</td><td>{item.currentBoxCode || "Sem caixa"}</td><td><span className={`badge status-${item.status}`}>{translateStatus(item.status)}</span></td><td>{originLabel(item.originType)}</td></tr>)}</tbody></table></div>}</section>

    <Dialog open={newOpen} onClose={() => !busy && setNewOpen(false)} title="Nova colônia" description="Cadastre a entidade biológica; a caixa é vinculada separadamente." size="large"><form className="form-grid" onSubmit={submitColony}><label className="field"><span>Meliponário</span><select autoFocus required value={form.meliponaryId} onChange={(e) => setForm({ ...form, meliponaryId: e.target.value, motherColonyId: "" })}><option value="">Selecione...</option>{meliponaries.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Espécie</span><select required value={form.speciesId} onChange={(e) => setForm({ ...form, speciesId: e.target.value, motherColonyId: "" })}><option value="">Selecione...</option>{species.map((item) => <option value={item.id} key={item.id}>{item.commonName}</option>)}</select></label><label className="field"><span>Código</span><input required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="Ex.: JAT-001" /></label><label className="field"><span>Origem</span><select value={form.originType} onChange={(e) => setForm({ ...form, originType: e.target.value })}>{originOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Data de instalação</span><input type="date" value={form.installedAt} onChange={(e) => setForm({ ...form, installedAt: e.target.value })} /></label><label className="field"><span>Colônia-mãe</span><select value={form.motherColonyId} onChange={(e) => setForm({ ...form, motherColonyId: e.target.value })}><option value="">Sem vínculo</option>{motherOptions.map((item) => <option value={item.id} key={item.id}>{item.code}</option>)}</select></label><label className="field full"><span>Detalhes da origem</span><input value={form.originNotes} onChange={(e) => setForm({ ...form, originNotes: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setNewOpen(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy}>{busy ? "Salvando..." : "Salvar colônia"}</button></div></form></Dialog>

    <Dialog open={placementOpen} onClose={() => !busy && setPlacementOpen(false)} title="Colocar ou mover para uma caixa" description="A ocupação anterior é encerrada e o histórico permanece preservado." size="medium"><form className="form-grid" onSubmit={submitPlacement}><label className="field full"><span>Colônia</span><select autoFocus required value={placement.colonyId} onChange={(e) => setPlacement({ ...placement, colonyId: e.target.value, boxId: "" })}><option value="">Selecione...</option>{items.filter((item) => manageableStatuses.has(item.status)).map((item) => <option value={item.id} key={item.id}>{item.code} {item.currentBoxCode ? `· atual ${item.currentBoxCode}` : "· sem caixa"}</option>)}</select></label><label className="field full"><span>Caixa ativa e livre</span><select required value={placement.boxId} onChange={(e) => setPlacement({ ...placement, boxId: e.target.value })}><option value="">Selecione...</option>{availableBoxes.map((box) => <option value={box.id} key={box.id}>{box.code}</option>)}</select></label><label className="field"><span>Data</span><input type="date" value={placement.startedAt} onChange={(e) => setPlacement({ ...placement, startedAt: e.target.value })} /></label><label className="field"><span>Motivo</span><input value={placement.reason} onChange={(e) => setPlacement({ ...placement, reason: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={3} value={placement.notes} onChange={(e) => setPlacement({ ...placement, notes: e.target.value })} /></label>{placement.colonyId && availableBoxes.length === 0 && <div className="inline-notice full">Não há caixa ativa e livre compatível com o meliponário desta colônia.</div>}<div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setPlacementOpen(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !placement.colonyId || availableBoxes.length === 0}>{busy ? "Salvando..." : "Registrar ocupação"}</button></div></form></Dialog>
  </div>;
}

function translateStatus(status: string) { const labels: Record<string, string> = { active: "Ativa", weak: "Fraca", recovering: "Em recuperação", lost: "Perdida", inactive: "Inativa", transferred: "Transferida" }; return labels[status] || status; }
function originLabel(origin: string) { return originOptions.find(([value]) => value === origin)?.[1] || origin; }
