import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Dialog } from "../components/Dialog";
import { PageToolbar } from "../components/PageToolbar";
import { listColonyMovements, listMovementDocuments } from "../lib/api";
import type { Colony, ColonyMovement, CreateMovementDocumentInput, CreateMovementInput, HiveBox, Meliponary, MovementDocument } from "../types";

type Props = { colonies: Colony[]; meliponaries: Meliponary[]; boxes: HiveBox[]; busy: boolean; onCreateMovement: (input: CreateMovementInput) => Promise<boolean>; onCreateDocument: (input: CreateMovementDocumentInput) => Promise<boolean>; };
const movementInitial: CreateMovementInput = { colonyId: "", movementType: "transport", movedAt: "", toMeliponaryId: "", toBoxId: "", destination: "", notes: "" };
const documentInitial: CreateMovementDocumentInput = { movementId: "", documentType: "gta", referenceNumber: "", sourceSystem: "", issuer: "", issuedAt: "", validUntil: "", filePath: "", notes: "" };

export function MovementsPage({ colonies, meliponaries, boxes, busy, onCreateMovement, onCreateDocument }: Props) {
  const [selectedColonyId, setSelectedColonyId] = useState("");
  const [movementForm, setMovementForm] = useState<CreateMovementInput>(movementInitial);
  const [documentForm, setDocumentForm] = useState<CreateMovementDocumentInput>(documentInitial);
  const [movements, setMovements] = useState<ColonyMovement[]>([]);
  const [documents, setDocuments] = useState<MovementDocument[]>([]);
  const [loading, setLoading] = useState(false);
  const [movementOpen, setMovementOpen] = useState(false);
  const [documentsOpen, setDocumentsOpen] = useState(false);
  const selectedMovementColony = colonies.find((c) => c.id === movementForm.colonyId);
  const movable = selectedMovementColony ? !["lost", "inactive", "transferred"].includes(selectedMovementColony.status) : false;
  const targetBoxes = useMemo(() => boxes.filter((box) => box.meliponaryId === movementForm.toMeliponaryId && box.status === "active" && !box.currentColonyCode), [boxes, movementForm.toMeliponaryId]);

  useEffect(() => { let cancelled = false; if (!selectedColonyId) { setMovements([]); return; } setLoading(true); listColonyMovements(selectedColonyId).then((items) => { if (!cancelled) setMovements(items); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [selectedColonyId]);
  useEffect(() => { let cancelled = false; if (!documentForm.movementId) { setDocuments([]); return; } listMovementDocuments(documentForm.movementId).then((items) => { if (!cancelled) setDocuments(items); }); return () => { cancelled = true; }; }, [documentForm.movementId]);

  async function reloadMovements(colonyId = selectedColonyId) { if (colonyId) setMovements(await listColonyMovements(colonyId)); }
  async function reloadDocuments(movementId = documentForm.movementId) { if (movementId) setDocuments(await listMovementDocuments(movementId)); }
  function openMovement() { setMovementForm({ ...movementInitial, colonyId: selectedColonyId }); setMovementOpen(true); }
  function openDocuments(movementId: string) { setDocumentForm({ ...documentInitial, movementId }); setDocumentsOpen(true); }
  async function submitMovement(event: FormEvent) { event.preventDefault(); const input: CreateMovementInput = { ...movementForm, movedAt: normalizeDateTime(movementForm.movedAt), toMeliponaryId: movementForm.movementType === "internal_transfer" ? movementForm.toMeliponaryId : undefined, toBoxId: movementForm.movementType === "internal_transfer" ? movementForm.toBoxId : undefined, destination: movementForm.movementType === "internal_transfer" ? undefined : movementForm.destination, documentReference: undefined }; if (await onCreateMovement(input)) { setSelectedColonyId(movementForm.colonyId); setMovementOpen(false); await reloadMovements(movementForm.colonyId); } }
  async function submitDocument(event: FormEvent) { event.preventDefault(); const input = { ...documentForm, issuedAt: normalizeDateTime(documentForm.issuedAt), validUntil: normalizeDateTime(documentForm.validUntil) }; if (await onCreateDocument(input)) { const movementId = documentForm.movementId; setDocumentForm({ ...documentInitial, movementId }); await reloadDocuments(movementId); } }

  return <div className="page-stack">
    <PageToolbar title="Movimentações" description="Deslocamentos e documentos vinculados à rastreabilidade do plantel." count={selectedColonyId ? `${movements.length} movimentações` : `${colonies.length} colônias`} primaryAction={{ label: "Nova movimentação", onClick: openMovement, disabled: busy || colonies.length === 0 }}><label className="toolbar-select"><span className="sr-only">Colônia</span><select value={selectedColonyId} onChange={(e) => setSelectedColonyId(e.target.value)}><option value="">Selecione uma colônia...</option>{colonies.map((c) => <option value={c.id} key={c.id}>{c.code}</option>)}</select></label></PageToolbar>
    <section className="panel wide-list"><div className="panel-heading"><h2>Histórico da colônia</h2><p>Transferências internas alteram localização; transporte preserva o estado atual.</p></div>{!selectedColonyId ? <div className="empty-list">Selecione uma colônia na toolbar.</div> : loading ? <div className="empty-list">Carregando...</div> : movements.length === 0 ? <div className="empty-list">Nenhuma movimentação registrada.</div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Origem</th><th>Destino</th><th>Documento</th></tr></thead><tbody>{movements.map((item) => <tr key={item.id}><td><strong>{formatDateTime(item.movedAt)}</strong></td><td>{movementLabel(item.movementType)}</td><td>{item.fromMeliponaryName}</td><td>{item.toMeliponaryName || item.destination || "—"}</td><td><button className="table-action" type="button" onClick={() => openDocuments(item.id)}>Documentos</button></td></tr>)}</tbody></table></div>}</section>

    <Dialog open={movementOpen} onClose={() => !busy && setMovementOpen(false)} title="Nova movimentação" description="Transferência interna altera a localização cadastrada; transporte não altera o estado atual." size="large"><form className="form-grid" onSubmit={submitMovement}><label className="field full"><span>Colônia</span><select autoFocus required value={movementForm.colonyId} onChange={(e) => setMovementForm({ ...movementForm, colonyId: e.target.value, toMeliponaryId: "", toBoxId: "" })}><option value="">Selecione...</option>{colonies.map((c) => <option value={c.id} key={c.id}>{c.code} · {c.status}</option>)}</select></label>{selectedMovementColony && !movable && <div className="inline-notice field full">Esta colônia não está disponível para nova movimentação.</div>}<label className="field"><span>Tipo</span><select value={movementForm.movementType} onChange={(e) => setMovementForm({ ...movementForm, movementType: e.target.value, toMeliponaryId: "", toBoxId: "", destination: "" })}><option value="transport">Transporte temporário</option><option value="internal_transfer">Transferência interna</option><option value="external_transfer">Transferência externa</option></select></label><label className="field"><span>Data e hora</span><input type="datetime-local" value={movementForm.movedAt} onChange={(e) => setMovementForm({ ...movementForm, movedAt: e.target.value })} /></label>{movementForm.movementType === "internal_transfer" ? <><label className="field full"><span>Meliponário de destino</span><select required value={movementForm.toMeliponaryId} onChange={(e) => setMovementForm({ ...movementForm, toMeliponaryId: e.target.value, toBoxId: "" })}><option value="">Selecione...</option>{meliponaries.filter((m) => m.id !== selectedMovementColony?.meliponaryId).map((m) => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="field full"><span>Caixa ativa e livre opcional</span><select value={movementForm.toBoxId} onChange={(e) => setMovementForm({ ...movementForm, toBoxId: e.target.value })}><option value="">Sem caixa definida</option>{targetBoxes.map((b) => <option value={b.id} key={b.id}>{b.code}</option>)}</select></label></> : <label className="field full"><span>Destino</span><input required value={movementForm.destination} onChange={(e) => setMovementForm({ ...movementForm, destination: e.target.value })} /></label>}<label className="field full"><span>Observações</span><textarea rows={3} value={movementForm.notes} onChange={(e) => setMovementForm({ ...movementForm, notes: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setMovementOpen(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !movementForm.colonyId || !movable}>{busy ? "Salvando..." : "Registrar movimentação"}</button></div></form></Dialog>

    <Dialog open={documentsOpen} onClose={() => !busy && setDocumentsOpen(false)} title="Documentos da movimentação" description="GTA, autorizações, notas, recibos, declarações, protocolos ou outros comprovantes." size="large"><div className="content-grid"><form className="form-grid" onSubmit={submitDocument}><label className="field"><span>Tipo</span><select value={documentForm.documentType} onChange={(e) => setDocumentForm({ ...documentForm, documentType: e.target.value })}><option value="gta">GTA</option><option value="authorization">Autorização</option><option value="invoice">Nota fiscal</option><option value="receipt">Recibo</option><option value="declaration">Declaração</option><option value="protocol">Protocolo</option><option value="certificate">Certificado</option><option value="other">Outro</option></select></label><label className="field"><span>Número / referência</span><input required value={documentForm.referenceNumber} onChange={(e) => setDocumentForm({ ...documentForm, referenceNumber: e.target.value })} /></label><label className="field"><span>Sistema de origem</span><input value={documentForm.sourceSystem} onChange={(e) => setDocumentForm({ ...documentForm, sourceSystem: e.target.value })} /></label><label className="field"><span>Emissor</span><input value={documentForm.issuer} onChange={(e) => setDocumentForm({ ...documentForm, issuer: e.target.value })} /></label><label className="field"><span>Emissão</span><input type="datetime-local" value={documentForm.issuedAt} onChange={(e) => setDocumentForm({ ...documentForm, issuedAt: e.target.value })} /></label><label className="field"><span>Validade</span><input type="datetime-local" value={documentForm.validUntil} onChange={(e) => setDocumentForm({ ...documentForm, validUntil: e.target.value })} /></label><label className="field full"><span>Caminho do arquivo opcional</span><input value={documentForm.filePath} onChange={(e) => setDocumentForm({ ...documentForm, filePath: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={2} value={documentForm.notes} onChange={(e) => setDocumentForm({ ...documentForm, notes: e.target.value })} /></label><div className="form-actions full"><button disabled={busy} type="submit">{busy ? "Salvando..." : "Vincular documento"}</button></div></form><div>{documents.length === 0 ? <div className="empty-list">Nenhum documento vinculado.</div> : <div className="record-list">{documents.map((doc) => <article className="record-card" key={doc.id}><div><strong>{documentLabel(doc.documentType)} · {doc.referenceNumber}</strong><span>{doc.sourceSystem || doc.issuer || "Sem emissor informado"}</span></div>{doc.notes && <p>{doc.notes}</p>}</article>)}</div>}</div></div></Dialog>
  </div>;
}
function normalizeDateTime(value?: string) { if (!value) return undefined; const n = value.replace("T", " "); return n.length === 16 ? `${n}:00` : n; }
function formatDateTime(value: string) { return value.replace("T", " ").slice(0, 16); }
function movementLabel(v: string) { return v === "internal_transfer" ? "Transferência interna" : v === "external_transfer" ? "Transferência externa" : "Transporte"; }
function documentLabel(v: string) { const l: Record<string,string> = { gta:"GTA", authorization:"Autorização", invoice:"Nota fiscal", receipt:"Recibo", declaration:"Declaração", protocol:"Protocolo", certificate:"Certificado", other:"Outro" }; return l[v] || v; }
