import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Dialog } from "../components/Dialog";
import { PageToolbar } from "../components/PageToolbar";
import { ReasonDialog } from "../components/ReasonDialog";
import { RecordActions } from "../components/RecordActions";
import { RecordStateBadge } from "../components/RecordStateBadge";
import type { RecordStateMap } from "../hooks/useAppData";
import { listColonyMovements, listMovementDocuments } from "../lib/api";
import type { Colony, ColonyMovement, CorrectMovementDetailsInput, CreateMovementDocumentInput, CreateMovementInput, HiveBox, Meliponary, MovementDocument, ReverseRecordInput, UpdateMovementDocumentInput, VoidRecordInput } from "../types";

type Props = {
  colonies: Colony[];
  meliponaries: Meliponary[];
  boxes: HiveBox[];
  busy: boolean;
  recordStateMap: RecordStateMap;
  onCreateMovement: (input: CreateMovementInput) => Promise<boolean>;
  onCreateDocument: (input: CreateMovementDocumentInput) => Promise<boolean>;
  onCorrectMovement: (input: CorrectMovementDetailsInput) => Promise<boolean>;
  onVoidTransport: (input: VoidRecordInput) => Promise<boolean>;
  onReverseMovement: (input: ReverseRecordInput) => Promise<boolean>;
  onUpdateDocument: (input: UpdateMovementDocumentInput) => Promise<boolean>;
  onVoidDocument: (input: VoidRecordInput) => Promise<boolean>;
};
const movementInitial: CreateMovementInput = { colonyId: "", movementType: "transport", movedAt: "", toMeliponaryId: "", toBoxId: "", destination: "", notes: "" };
const documentInitial: CreateMovementDocumentInput = { movementId: "", documentType: "gta", referenceNumber: "", sourceSystem: "", issuer: "", issuedAt: "", validUntil: "", filePath: "", notes: "" };

export function MovementsPage({ colonies, meliponaries, boxes, busy, recordStateMap, onCreateMovement, onCreateDocument, onCorrectMovement, onVoidTransport, onReverseMovement, onUpdateDocument, onVoidDocument }: Props) {
  const [selectedColonyId, setSelectedColonyId] = useState("");
  const [movementForm, setMovementForm] = useState<CreateMovementInput>(movementInitial);
  const [documentForm, setDocumentForm] = useState<CreateMovementDocumentInput>(documentInitial);
  const [movements, setMovements] = useState<ColonyMovement[]>([]);
  const [documents, setDocuments] = useState<MovementDocument[]>([]);
  const [loading, setLoading] = useState(false);
  const [movementOpen, setMovementOpen] = useState(false);
  const [documentsOpen, setDocumentsOpen] = useState(false);
  const [movementDetail, setMovementDetail] = useState<ColonyMovement | null>(null);
  const [movementEdit, setMovementEdit] = useState<CorrectMovementDetailsInput | null>(null);
  const [movementAction, setMovementAction] = useState<{ item: ColonyMovement; mode: "void" | "reverse" } | null>(null);
  const [documentDetail, setDocumentDetail] = useState<MovementDocument | null>(null);
  const [documentEdit, setDocumentEdit] = useState<UpdateMovementDocumentInput | null>(null);
  const [documentVoid, setDocumentVoid] = useState<MovementDocument | null>(null);
  const selectedMovementColony = colonies.find((c) => c.id === movementForm.colonyId);
  const movable = selectedMovementColony ? !["lost", "inactive", "transferred"].includes(selectedMovementColony.status) : false;
  const targetBoxes = useMemo(() => boxes.filter((box) => box.meliponaryId === movementForm.toMeliponaryId && box.status === "active" && !box.currentColonyCode), [boxes, movementForm.toMeliponaryId]);

  useEffect(() => { void reloadMovements(selectedColonyId); }, [selectedColonyId]);
  useEffect(() => { void reloadDocuments(documentForm.movementId); }, [documentForm.movementId]);
  async function reloadMovements(colonyId = selectedColonyId) { if (!colonyId) { setMovements([]); return; } setLoading(true); try { setMovements(await listColonyMovements(colonyId)); } finally { setLoading(false); } }
  async function reloadDocuments(movementId = documentForm.movementId) { if (!movementId) { setDocuments([]); return; } setDocuments(await listMovementDocuments(movementId)); }
  function openMovement() { setMovementForm({ ...movementInitial, colonyId: selectedColonyId }); setMovementOpen(true); }
  function openDocuments(movementId: string) { setDocumentForm({ ...documentInitial, movementId }); setDocumentsOpen(true); }
  async function submitMovement(event: FormEvent) { event.preventDefault(); const input: CreateMovementInput = { ...movementForm, movedAt: normalizeDateTime(movementForm.movedAt), toMeliponaryId: movementForm.movementType === "internal_transfer" ? movementForm.toMeliponaryId : undefined, toBoxId: movementForm.movementType === "internal_transfer" ? movementForm.toBoxId : undefined, destination: movementForm.movementType === "internal_transfer" ? undefined : movementForm.destination, documentReference: undefined }; if (await onCreateMovement(input)) { setSelectedColonyId(movementForm.colonyId); setMovementOpen(false); await reloadMovements(movementForm.colonyId); } }
  async function submitDocument(event: FormEvent) { event.preventDefault(); const input = { ...documentForm, issuedAt: normalizeDateTime(documentForm.issuedAt), validUntil: normalizeDateTime(documentForm.validUntil) }; if (await onCreateDocument(input)) { const movementId = documentForm.movementId; setDocumentForm({ ...documentInitial, movementId }); await reloadDocuments(movementId); } }
  function beginMovementEdit(item: ColonyMovement) { setMovementEdit({ id: item.id, reason: "", destination: item.destination || undefined, notes: item.notes || "" }); }
  async function submitMovementEdit(event: FormEvent) { event.preventDefault(); if (!movementEdit) return; if (await onCorrectMovement(movementEdit)) { setMovementEdit(null); await reloadMovements(); } }
  function beginDocumentEdit(doc: MovementDocument) { setDocumentEdit({ id: doc.id, reason: "", documentType: doc.documentType, referenceNumber: doc.referenceNumber, sourceSystem: doc.sourceSystem || "", issuer: doc.issuer || "", issuedAt: doc.issuedAt ? toInputDateTime(doc.issuedAt) : "", validUntil: doc.validUntil ? toInputDateTime(doc.validUntil) : "", filePath: doc.filePath || "", notes: doc.notes || "" }); }
  async function submitDocumentEdit(event: FormEvent) { event.preventDefault(); if (!documentEdit) return; const payload: UpdateMovementDocumentInput = { ...documentEdit, issuedAt: normalizeDateTime(documentEdit.issuedAt), validUntil: normalizeDateTime(documentEdit.validUntil) }; if (await onUpdateDocument(payload)) { setDocumentEdit(null); await reloadDocuments(); } }

  return <div className="page-stack">
    <PageToolbar title="Movimentações" description="Deslocamentos e documentos vinculados à rastreabilidade do plantel." count={selectedColonyId ? `${movements.length} movimentações` : `${colonies.length} colônias`} primaryAction={{ label: "Nova movimentação", onClick: openMovement, disabled: busy || colonies.length === 0 }}><label className="toolbar-select"><span className="sr-only">Colônia</span><select value={selectedColonyId} onChange={(e) => setSelectedColonyId(e.target.value)}><option value="">Selecione uma colônia...</option>{colonies.map((c) => <option value={c.id} key={c.id}>{c.code}</option>)}</select></label></PageToolbar>
    <section className="panel wide-list"><div className="panel-heading"><h2>Histórico da colônia</h2><p>Transporte pode ser anulado. Transferências alteram estado e localização e, por isso, usam reversão transacional controlada.</p></div>{!selectedColonyId ? <div className="empty-list">Selecione uma colônia na toolbar.</div> : loading ? <div className="empty-list">Carregando...</div> : movements.length === 0 ? <div className="empty-list">Nenhuma movimentação registrada.</div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Origem</th><th>Destino</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{movements.map((item) => { const state = recordStateMap.get(`movement:${item.id}`); const disabled = Boolean(state?.voidedAt || state?.reversedAt); return <tr key={item.id} className={disabled ? "voided-row" : undefined}><td><strong>{formatDateTime(item.movedAt)}</strong></td><td>{movementLabel(item.movementType)}</td><td>{item.fromMeliponaryName}</td><td>{item.toMeliponaryName || item.destination || "—"}</td><td><RecordStateBadge state={state} /></td><td><RecordActions busy={busy} onOpen={() => setMovementDetail(item)} onEdit={disabled ? undefined : () => beginMovementEdit(item)} secondary={[{ label: "Documentos", onClick: () => openDocuments(item.id) }, item.movementType === "transport" ? { label: "Anular transporte", onClick: () => setMovementAction({ item, mode: "void" }), disabled, danger: true } : { label: "Reverter transferência", onClick: () => setMovementAction({ item, mode: "reverse" }), disabled, danger: true }]} /></td></tr>; })}</tbody></table></div>}</section>

    <Dialog open={movementOpen} onClose={() => !busy && setMovementOpen(false)} title="Nova movimentação" description="Transferência interna altera a localização cadastrada; transporte não altera o estado atual." size="large"><form className="form-grid" onSubmit={submitMovement}><label className="field full"><span>Colônia</span><select autoFocus required value={movementForm.colonyId} onChange={(e) => setMovementForm({ ...movementForm, colonyId: e.target.value, toMeliponaryId: "", toBoxId: "" })}><option value="">Selecione...</option>{colonies.map((c) => <option value={c.id} key={c.id}>{c.code} · {c.status}</option>)}</select></label>{selectedMovementColony && !movable && <div className="inline-notice field full">Esta colônia não está disponível para nova movimentação.</div>}<label className="field"><span>Tipo</span><select value={movementForm.movementType} onChange={(e) => setMovementForm({ ...movementForm, movementType: e.target.value, toMeliponaryId: "", toBoxId: "", destination: "" })}><option value="transport">Transporte temporário</option><option value="internal_transfer">Transferência interna</option><option value="external_transfer">Transferência externa</option></select></label><label className="field"><span>Data e hora</span><input type="datetime-local" value={movementForm.movedAt} onChange={(e) => setMovementForm({ ...movementForm, movedAt: e.target.value })} /></label>{movementForm.movementType === "internal_transfer" ? <><label className="field full"><span>Meliponário de destino</span><select required value={movementForm.toMeliponaryId} onChange={(e) => setMovementForm({ ...movementForm, toMeliponaryId: e.target.value, toBoxId: "" })}><option value="">Selecione...</option>{meliponaries.filter((m) => !m.archivedAt && m.id !== selectedMovementColony?.meliponaryId).map((m) => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="field full"><span>Caixa ativa e livre opcional</span><select value={movementForm.toBoxId} onChange={(e) => setMovementForm({ ...movementForm, toBoxId: e.target.value })}><option value="">Sem caixa definida</option>{targetBoxes.map((b) => <option value={b.id} key={b.id}>{b.code}</option>)}</select></label></> : <label className="field full"><span>Destino</span><input required value={movementForm.destination} onChange={(e) => setMovementForm({ ...movementForm, destination: e.target.value })} /></label>}<label className="field full"><span>Observações</span><textarea rows={3} value={movementForm.notes} onChange={(e) => setMovementForm({ ...movementForm, notes: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setMovementOpen(false)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !movementForm.colonyId || !movable}>{busy ? "Salvando..." : "Registrar movimentação"}</button></div></form></Dialog>

    <Dialog open={Boolean(movementDetail)} onClose={() => setMovementDetail(null)} title="Movimentação" description={movementDetail ? `${movementDetail.colonyCode} · ${formatDateTime(movementDetail.movedAt)}` : ""} size="medium">{movementDetail && <div className="detail-grid"><div><span>Tipo</span><strong>{movementLabel(movementDetail.movementType)}</strong></div><div><span>Origem</span><strong>{movementDetail.fromMeliponaryName}</strong></div><div><span>Caixa de origem</span><strong>{movementDetail.fromBoxCode || "—"}</strong></div><div><span>Destino</span><strong>{movementDetail.toMeliponaryName || movementDetail.destination || "—"}</strong></div><div><span>Caixa de destino</span><strong>{movementDetail.toBoxCode || "—"}</strong></div><div className="full"><span>Observações</span><p>{movementDetail.notes || "—"}</p></div></div>}</Dialog>
    <Dialog open={Boolean(movementEdit)} onClose={() => !busy && setMovementEdit(null)} title="Corrigir dados descritivos" description="Tipo, data e relações de transferência são consequenciais e não são reescritos por esta edição." size="medium">{movementEdit && <form className="form-grid" onSubmit={submitMovementEdit}><label className="field full"><span>Destino textual</span><input value={movementEdit.destination || ""} onChange={(e) => setMovementEdit({ ...movementEdit, destination: e.target.value || undefined })} /></label><label className="field full"><span>Observações</span><textarea rows={3} value={movementEdit.notes || ""} onChange={(e) => setMovementEdit({ ...movementEdit, notes: e.target.value })} /></label><label className="field full"><span>Motivo da correção</span><textarea required rows={3} value={movementEdit.reason} onChange={(e) => setMovementEdit({ ...movementEdit, reason: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setMovementEdit(null)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !movementEdit.reason.trim()}>Salvar correção</button></div></form>}</Dialog>

    <Dialog open={documentsOpen} onClose={() => !busy && setDocumentsOpen(false)} title="Documentos da movimentação" description="Documentos podem ser corrigidos ou invalidados sem perder a referência histórica." size="large"><div className="content-grid"><form className="form-grid" onSubmit={submitDocument}><label className="field"><span>Tipo</span><select value={documentForm.documentType} onChange={(e) => setDocumentForm({ ...documentForm, documentType: e.target.value })}>{documentTypeOptions()}</select></label><label className="field"><span>Número / referência</span><input required value={documentForm.referenceNumber} onChange={(e) => setDocumentForm({ ...documentForm, referenceNumber: e.target.value })} /></label><label className="field"><span>Sistema de origem</span><input value={documentForm.sourceSystem} onChange={(e) => setDocumentForm({ ...documentForm, sourceSystem: e.target.value })} /></label><label className="field"><span>Emissor</span><input value={documentForm.issuer} onChange={(e) => setDocumentForm({ ...documentForm, issuer: e.target.value })} /></label><label className="field"><span>Emissão</span><input type="datetime-local" value={documentForm.issuedAt} onChange={(e) => setDocumentForm({ ...documentForm, issuedAt: e.target.value })} /></label><label className="field"><span>Validade</span><input type="datetime-local" value={documentForm.validUntil} onChange={(e) => setDocumentForm({ ...documentForm, validUntil: e.target.value })} /></label><label className="field full"><span>Caminho do arquivo opcional</span><input value={documentForm.filePath} onChange={(e) => setDocumentForm({ ...documentForm, filePath: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={2} value={documentForm.notes} onChange={(e) => setDocumentForm({ ...documentForm, notes: e.target.value })} /></label><div className="form-actions full"><button disabled={busy} type="submit">{busy ? "Salvando..." : "Vincular documento"}</button></div></form><div>{documents.length === 0 ? <div className="empty-list">Nenhum documento vinculado.</div> : <div className="record-list">{documents.map((doc) => { const state = recordStateMap.get(`movement_document:${doc.id}`); return <article className={state?.voidedAt ? "record-card voided-row" : "record-card"} key={doc.id}><div className="record-title-row"><div><strong>{documentLabel(doc.documentType)} · {doc.referenceNumber}</strong><span>{doc.sourceSystem || doc.issuer || "Sem emissor informado"}</span></div><RecordStateBadge state={state} /></div>{doc.notes && <p>{doc.notes}</p>}<RecordActions busy={busy} onOpen={() => setDocumentDetail(doc)} onEdit={state?.voidedAt ? undefined : () => beginDocumentEdit(doc)} secondary={[{ label: "Invalidar", onClick: () => setDocumentVoid(doc), disabled: Boolean(state?.voidedAt), danger: true }]} /></article>; })}</div>}</div></div></Dialog>

    <Dialog open={Boolean(documentDetail)} onClose={() => setDocumentDetail(null)} title="Documento" description={documentDetail ? `${documentLabel(documentDetail.documentType)} · ${documentDetail.referenceNumber}` : ""} size="medium">{documentDetail && <div className="detail-grid"><div><span>Sistema</span><strong>{documentDetail.sourceSystem || "—"}</strong></div><div><span>Emissor</span><strong>{documentDetail.issuer || "—"}</strong></div><div><span>Emissão</span><strong>{documentDetail.issuedAt ? formatDateTime(documentDetail.issuedAt) : "—"}</strong></div><div><span>Validade</span><strong>{documentDetail.validUntil ? formatDateTime(documentDetail.validUntil) : "—"}</strong></div><div className="full"><span>Arquivo</span><p>{documentDetail.filePath || "—"}</p></div><div className="full"><span>Observações</span><p>{documentDetail.notes || "—"}</p></div></div>}</Dialog>
    <Dialog open={Boolean(documentEdit)} onClose={() => !busy && setDocumentEdit(null)} title="Editar documento" description="A versão anterior permanece na auditoria." size="large">{documentEdit && <form className="form-grid" onSubmit={submitDocumentEdit}><label className="field"><span>Tipo</span><select value={documentEdit.documentType} onChange={(e) => setDocumentEdit({ ...documentEdit, documentType: e.target.value })}>{documentTypeOptions()}</select></label><label className="field"><span>Número / referência</span><input required value={documentEdit.referenceNumber} onChange={(e) => setDocumentEdit({ ...documentEdit, referenceNumber: e.target.value })} /></label><label className="field"><span>Sistema de origem</span><input value={documentEdit.sourceSystem || ""} onChange={(e) => setDocumentEdit({ ...documentEdit, sourceSystem: e.target.value })} /></label><label className="field"><span>Emissor</span><input value={documentEdit.issuer || ""} onChange={(e) => setDocumentEdit({ ...documentEdit, issuer: e.target.value })} /></label><label className="field"><span>Emissão</span><input type="datetime-local" value={documentEdit.issuedAt || ""} onChange={(e) => setDocumentEdit({ ...documentEdit, issuedAt: e.target.value })} /></label><label className="field"><span>Validade</span><input type="datetime-local" value={documentEdit.validUntil || ""} onChange={(e) => setDocumentEdit({ ...documentEdit, validUntil: e.target.value })} /></label><label className="field full"><span>Caminho do arquivo</span><input value={documentEdit.filePath || ""} onChange={(e) => setDocumentEdit({ ...documentEdit, filePath: e.target.value })} /></label><label className="field full"><span>Observações</span><textarea rows={2} value={documentEdit.notes || ""} onChange={(e) => setDocumentEdit({ ...documentEdit, notes: e.target.value })} /></label><label className="field full"><span>Motivo da edição</span><textarea required rows={3} value={documentEdit.reason} onChange={(e) => setDocumentEdit({ ...documentEdit, reason: e.target.value })} /></label><div className="form-actions full"><button className="button-secondary" type="button" onClick={() => setDocumentEdit(null)} disabled={busy}>Cancelar</button><button type="submit" disabled={busy || !documentEdit.reason.trim() || !documentEdit.referenceNumber.trim()}>Salvar documento</button></div></form>}</Dialog>

    <ReasonDialog open={Boolean(movementAction)} title={movementAction?.mode === "reverse" ? "Reverter transferência?" : "Anular transporte?"} description={movementAction ? `${movementAction.item.colonyCode} · ${formatDateTime(movementAction.item.movedAt)}` : ""} confirmLabel={movementAction?.mode === "reverse" ? "Reverter transferência" : "Anular transporte"} consequence={movementAction?.mode === "reverse" ? "A reversão tenta restaurar meliponário, situação e caixa anteriores. Qualquer consequência posterior incompatível bloqueia toda a operação." : "O transporte continuará auditável, mas deixará de representar um fato operacional válido."} danger busy={busy} onClose={() => setMovementAction(null)} onConfirm={async (reason) => { if (!movementAction) return false; const payload = { id: movementAction.item.id, reason }; const ok = movementAction.mode === "reverse" ? await onReverseMovement(payload) : await onVoidTransport(payload); if (ok) await reloadMovements(); return ok; }} />
    <ReasonDialog open={Boolean(documentVoid)} title="Invalidar documento?" description={documentVoid ? `${documentLabel(documentVoid.documentType)} · ${documentVoid.referenceNumber}` : ""} confirmLabel="Invalidar documento" consequence="O vínculo e a referência permanecerão preservados na auditoria, mas o documento deixará de ser considerado válido." danger busy={busy} onClose={() => setDocumentVoid(null)} onConfirm={async (reason) => { if (!documentVoid) return false; const ok = await onVoidDocument({ id: documentVoid.id, reason }); if (ok) await reloadDocuments(); return ok; }} />
  </div>;
}
function normalizeDateTime(value?: string) { if (!value) return undefined; const n = value.replace("T", " "); return n.length === 16 ? `${n}:00` : n; }
function toInputDateTime(value: string) { return value.replace(" ", "T").slice(0, 16); }
function formatDateTime(value: string) { return value.replace("T", " ").slice(0, 16); }
function movementLabel(v: string) { return v === "internal_transfer" ? "Transferência interna" : v === "external_transfer" ? "Transferência externa" : "Transporte"; }
function documentLabel(v: string) { const l: Record<string,string> = { gta:"GTA", authorization:"Autorização", invoice:"Nota fiscal", receipt:"Recibo", declaration:"Declaração", protocol:"Protocolo", certificate:"Certificado", other:"Outro" }; return l[v] || v; }
function documentTypeOptions() { return <><option value="gta">GTA</option><option value="authorization">Autorização</option><option value="invoice">Nota fiscal</option><option value="receipt">Recibo</option><option value="declaration">Declaração</option><option value="protocol">Protocolo</option><option value="certificate">Certificado</option><option value="other">Outro</option></>; }
